/** Control tailoring helpers. Keep mutations additive for unrelated controls. */

export function overlayFlags(intake) {
  const selected = [];
  if (intake?.overlayNistModerate) selected.push("nist-moderate");
  if (intake?.overlayCnssi1253) selected.push("cnssi-1253");
  if (intake?.overlayDodRmf) selected.push("dod-rmf");
  if (intake?.overlayPrivacy) selected.push("privacy");
  return selected;
}

export function isControlSelected(intake, overlays) {
  const selected = overlayFlags(intake);
  return (overlays ?? []).some((overlay) => selected.includes(overlay));
}

export function patchControl(pkg, id, partial) {
  const current = pkg.controls[id];
  return {
    ...pkg,
    controls: {
      ...pkg.controls,
      [id]: { ...current, ...partial },
    },
  };
}

function emptyControl(id) {
  return {
    controlId: id,
    selection: "in-scope",
    implementation: "not-implemented",
    inheritedFrom: "",
    inheritanceSourceId: "",
    naJustification: "",
    implementationStatement: "",
    responsibleRole: "ISSO",
    parameters: "",
    assessment: "not-started",
    notes: "",
  };
}

export function retargetControls(pkg, catalog) {
  const next = { ...pkg, controls: { ...pkg.controls } };
  for (const item of catalog) {
    const selected = isControlSelected(pkg.intake, item.overlays);
    if (!selected) {
      delete next.controls[item.id];
      continue;
    }
    if (!next.controls[item.id]) {
      next.controls[item.id] = emptyControl(item.id);
    }
  }
  const policyIds = new Set(
    catalog.filter((item) => item.policyControl && isControlSelected(pkg.intake, item.overlays)).map((item) => item.id),
  );
  const existing = new Map((pkg.policies ?? []).map((policy) => [policy.controlId, policy]));
  next.policies = [...policyIds].map((id) => {
    const found = existing.get(id);
    if (found) return found;
    const item = catalog.find((entry) => entry.id === id);
    return {
      id: `pol-${id}`,
      controlId: id,
      title: `${id} ${item?.title ?? ""}`.trim(),
      status: "stub",
      owner: "ISSO",
      body: `# ${id} ${item?.title ?? ""}\n\nStub generated by A&A Workbench. Expand before SCA freeze.\n`,
      lastUpdated: new Date().toISOString().slice(0, 10),
    };
  });
  return next;
}
